# 已知问题

|API|问题总数|错误数|疑惑数|
|----|:----:|:----:|:----:|
|torch.tensor| 1 | 0 | 1 |
|torch.abs| | | |
|torch.acos| | | |
|torch.cos| | | |
|torch.kthvalue| | | |
## torch.tensor

### 疑惑.1 inf问题

对某个浮点数`x`如果在`torch.tensor`中被识别为`inf`或者`-inf`,那么将不会满足`x+(-x) == 0`的性质；
于此同时`x+(-x)`的结果将是`tensor([nan])`。

## torch.kthvalue

### 未知
#10920  REDUCE cov: 14 ft: 50 corp: 9/247b lim: 74 exec/s: 364 rss: 231Mb L: 21/44 MS: 1 EraseBytes-

**<font color=red>=== Uncaught Python exception: ===</font>**

AssertionError: 

Traceback (most recent call last):
  File "hypothesis/core.py", line 1278, in fuzz_one_input
  File "hypothesis/core.py", line 661, in execute_once
  File "hypothesis/executors.py", line 47, in default_new_style_executor
  File "hypothesis/core.py", line 657, in run
  File "kthvalue_fuzzer.py", line 64, in torch_kthvalue_test
  File "kthvalue_fuzzer.py", line 42, in check_kthvalue

==16== ERROR: libFuzzer: fuzz target exited
SUMMARY: libFuzzer: fuzz target exited
MS: 2 InsertRepeatedBytes-CrossOver-; base unit: 4bb16998fe296c3241dacc525a02edf9d139fd90
0x27,0xff,0xff,0xb0,0x91,0xff,0xb1,0x0,0xb1,0x0,0x1,0xb1,0xfe,0x0,0x0,0x0,0x0,0x0,0xff,0xff,0x0,0x0,0x0,0x0,0xff,0xfb,0x0,0x0,0x0,0x0,0x10,0xb1,0xb1,0xff,0xff,0x2,0x0,0x0,0x0,0x0,0xff,0xfb,0x0,0x0,0x0,0x0,0x10,0xb1,0xb1,0xb1,0xb1,0x0,0xb1,0xb1,
'\377\377\260\221\377\261\000\261\000\001\261\376\000\000\000\000\000\377\377\000\000\000\000\377\373\000\000\000\000\020\261\261\377\377\002\000\000\000\000\377\373\000\000\000\000\020\261\261\261\261\000\261\261
artifact_prefix='./'; Test unit written to ./crash-4b42c978be2ef0ad3a4531e068713cc37ccb6d45
Base64: J///sJH/sQCxAAGx/gAAAAAA//8AAAAA//sAAAAAELGx//8CAAAAAP/7AAAAABCxsbGxALGx